package rebue.rna.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   认证成功用户信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RNA_REALNAME
 *
 * @mbg.generated do_not_delete_during_merge 2018-06-08 19:17:41
 */
@ApiModel(value = "RnaRealnameMo", description = "认证成功用户信息表")
@JsonInclude(Include.NON_NULL)
public class RnaRealnameMo implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_REALNAME.ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   用户真名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_REALNAME.REAL_NAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "用户真名")
    private String realName;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_REALNAME.ID_CARD
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "身份证号")
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_REALNAME.ID
     *
     * @return the value of RNA_REALNAME.ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_REALNAME.ID
     *
     * @param id the value for RNA_REALNAME.ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_REALNAME.REAL_NAME
     *
     * @return the value of RNA_REALNAME.REAL_NAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_REALNAME.REAL_NAME
     *
     * @param realName the value for RNA_REALNAME.REAL_NAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_REALNAME.ID_CARD
     *
     * @return the value of RNA_REALNAME.ID_CARD
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_REALNAME.ID_CARD
     *
     * @param idCard the value for RNA_REALNAME.ID_CARD
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", realName=").append(realName);
        sb.append(", idCard=").append(idCard);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RnaRealnameMo other = (RnaRealnameMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}