package rebue.rna.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   用户实名认证审核
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RNA_VERIFY
 *
 * @mbg.generated do_not_delete_during_merge 2018-06-08 19:17:41
 */
@ApiModel(value = "RnaVerifyMo", description = "用户实名认证审核")
@JsonInclude(Include.NON_NULL)
public class RnaVerifyMo implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.USER_ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "用户ID")
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户真名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.REAL_NAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "用户真名")
    private String realName;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.ID_CARD
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "身份证号")
    private String idCard;

    /**
     * Database Column Remarks:
     *   申请状态：-1 取消申请，1 待审核 ，2 审核中，3 已拒绝 ，4 已通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.APPLY_STATE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "申请状态：-1 取消申请，1 待审核 ，2 审核中，3 已拒绝 ，4 已通过")
    private Byte applyState;

    /**
     * Database Column Remarks:
     *   申请时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.APPLY_TIME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "申请时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date applyTime;

    /**
     * Database Column Remarks:
     *   申请类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.APPLY_TYPE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "申请类型")
    private Byte applyType;

    /**
     * Database Column Remarks:
     *   审核人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.VERIFiER_ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "审核人ID")
    private Long verifierId;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.VERIFY_TIME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "审核时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date verifyTime;

    /**
     * Database Column Remarks:
     *   拒绝原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.REJECT_REASON
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "拒绝原因")
    private String rejectReason;

    /**
     * Database Column Remarks:
     *   审核图片1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.PIC_ONE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "审核图片1")
    private String picOne;

    /**
     * Database Column Remarks:
     *   审核图片2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.PIC_TWO
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "审核图片2")
    private String picTwo;

    /**
     * Database Column Remarks:
     *   审核图片3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.PIC_THREE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "审核图片3")
    private String picThree;

    /**
     * Database Column Remarks:
     *   审核图片4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RNA_VERIFY.PIC_FOUR
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @ApiModelProperty(value = "审核图片4")
    private String picFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.ID
     *
     * @return the value of RNA_VERIFY.ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.ID
     *
     * @param id the value for RNA_VERIFY.ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.USER_ID
     *
     * @return the value of RNA_VERIFY.USER_ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.USER_ID
     *
     * @param userId the value for RNA_VERIFY.USER_ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.REAL_NAME
     *
     * @return the value of RNA_VERIFY.REAL_NAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.REAL_NAME
     *
     * @param realName the value for RNA_VERIFY.REAL_NAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.ID_CARD
     *
     * @return the value of RNA_VERIFY.ID_CARD
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.ID_CARD
     *
     * @param idCard the value for RNA_VERIFY.ID_CARD
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.APPLY_STATE
     *
     * @return the value of RNA_VERIFY.APPLY_STATE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Byte getApplyState() {
        return applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.APPLY_STATE
     *
     * @param applyState the value for RNA_VERIFY.APPLY_STATE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setApplyState(Byte applyState) {
        this.applyState = applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.APPLY_TIME
     *
     * @return the value of RNA_VERIFY.APPLY_TIME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.APPLY_TIME
     *
     * @param applyTime the value for RNA_VERIFY.APPLY_TIME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.APPLY_TYPE
     *
     * @return the value of RNA_VERIFY.APPLY_TYPE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Byte getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.APPLY_TYPE
     *
     * @param applyType the value for RNA_VERIFY.APPLY_TYPE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setApplyType(Byte applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.VERIFiER_ID
     *
     * @return the value of RNA_VERIFY.VERIFiER_ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Long getVerifierId() {
        return verifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.VERIFiER_ID
     *
     * @param verifierId the value for RNA_VERIFY.VERIFiER_ID
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setVerifierId(Long verifierId) {
        this.verifierId = verifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.VERIFY_TIME
     *
     * @return the value of RNA_VERIFY.VERIFY_TIME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public Date getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.VERIFY_TIME
     *
     * @param verifyTime the value for RNA_VERIFY.VERIFY_TIME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setVerifyTime(Date verifyTime) {
        this.verifyTime = verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.REJECT_REASON
     *
     * @return the value of RNA_VERIFY.REJECT_REASON
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.REJECT_REASON
     *
     * @param rejectReason the value for RNA_VERIFY.REJECT_REASON
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.PIC_ONE
     *
     * @return the value of RNA_VERIFY.PIC_ONE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getPicOne() {
        return picOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.PIC_ONE
     *
     * @param picOne the value for RNA_VERIFY.PIC_ONE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setPicOne(String picOne) {
        this.picOne = picOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.PIC_TWO
     *
     * @return the value of RNA_VERIFY.PIC_TWO
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getPicTwo() {
        return picTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.PIC_TWO
     *
     * @param picTwo the value for RNA_VERIFY.PIC_TWO
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setPicTwo(String picTwo) {
        this.picTwo = picTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.PIC_THREE
     *
     * @return the value of RNA_VERIFY.PIC_THREE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getPicThree() {
        return picThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.PIC_THREE
     *
     * @param picThree the value for RNA_VERIFY.PIC_THREE
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setPicThree(String picThree) {
        this.picThree = picThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RNA_VERIFY.PIC_FOUR
     *
     * @return the value of RNA_VERIFY.PIC_FOUR
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public String getPicFour() {
        return picFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RNA_VERIFY.PIC_FOUR
     *
     * @param picFour the value for RNA_VERIFY.PIC_FOUR
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    public void setPicFour(String picFour) {
        this.picFour = picFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", realName=").append(realName);
        sb.append(", idCard=").append(idCard);
        sb.append(", applyState=").append(applyState);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", applyType=").append(applyType);
        sb.append(", verifierId=").append(verifierId);
        sb.append(", verifyTime=").append(verifyTime);
        sb.append(", rejectReason=").append(rejectReason);
        sb.append(", picOne=").append(picOne);
        sb.append(", picTwo=").append(picTwo);
        sb.append(", picThree=").append(picThree);
        sb.append(", picFour=").append(picFour);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RnaVerifyMo other = (RnaVerifyMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}