package rebue.rna.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.rna.mo.RnaRealnameMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface RnaRealnameMapper extends MybatisBaseMapper<RnaRealnameMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int insert(RnaRealnameMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int insertSelective(RnaRealnameMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    RnaRealnameMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int updateByPrimaryKeySelective(RnaRealnameMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int updateByPrimaryKey(RnaRealnameMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    List<RnaRealnameMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    List<RnaRealnameMo> selectSelective(RnaRealnameMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_REALNAME
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    boolean existSelective(RnaRealnameMo record);
}