package rebue.rna.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.rna.mo.RnaVerifyMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface RnaVerifyMapper extends MybatisBaseMapper<RnaVerifyMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int insert(RnaVerifyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int insertSelective(RnaVerifyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    RnaVerifyMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int updateByPrimaryKeySelective(RnaVerifyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    int updateByPrimaryKey(RnaVerifyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    List<RnaVerifyMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    List<RnaVerifyMo> selectSelective(RnaVerifyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RNA_VERIFY
     *
     * @mbg.generated 2018-06-08 19:17:41
     */
    boolean existSelective(RnaVerifyMo record);
}